package phrases

const (
	StartCommandDescription     = "Starts the game"
	GameExistsResponseContent   = ":x: The game has already started"
	GameInvitationTitle         = "Game invitation"
	GameInvitationDescription   = "New game invitation"
	GameInvitationJoinLabel     = "Join"
	GameInvitationErrNotFound   = "error while joining: cannot find this game"
	GameInvitationErrUserExists = "user has already joined"
	GameInvitationErrExists     = "game already exists"
	GameInvitationStartLabel    = "Start match"
	GameInvitationJoinedPlayers = "Joined players"
	GameInvitationStarting      = "Starting the game..."
	CurrentRoundMessageContent  = "Guess where it is (round %d / %d)"
	RoundEndedTitle             = "Round ended (%d / %d)"
	RoundEndedText              = "Round ended! Correct country:"
	RoundEndedWinners           = "Winners:"
	RoundEndedUserScore         = "(+1 point, total: %d)"
	RoundEndedNoWinners         = "There are no winners"
	RoundEndedRestartText       = "Press ▶ emoji to start the next round"
	MatchEndedTitle             = "Match ended"
	PlayerRating                = ":trophy: Player rating:"
	PlayerPoints                = "(%d points)"
)
